POST http://localhost/Proyecto2-Grupo09/src/api/sesion/index.php
Content-Type: application/x-www-form-urlencoded

email=javierruperez13@gamil.com&password=1234

### Devolver todos los usuarios

GET http://localhost/Proyecto2-Grupo09/src/api/usuarios

### Crear un usuario

POST http://localhost/Proyecto2-Grupo09/src/api/usuarios
Content-Type: application/x-www-form-urlencoded

nombre=Desgraciado Jiménez&password=1234&rol=4&email=cojones@gamil.com&dirección=Calle de la amargura 123&telefono=123456789&DNI=20962030&username=desjim

### Actualizar un usuario

PUT http://localhost/Proyecto2-Grupo09/src/api/usuarios/31
Content-Type: application/json

{"nombre": "Miguelito Calamardo","idRol": "4","DNI": "20962032A","password": "1234", "direccion": "Calle de la amargura nº123"}

### Eliminar señor Jiménez

DELETE http://localhost/Proyecto2-Grupo09/src/api/usuarios/26
