insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (1, 1, 'terraza', 'Dallas');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (2, 2, 'patio', 'Millisent');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (3, 3, 'terraza', 'Artur');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (4, 4, 'baño', 'Ebba');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (5, 5, 'habitación 1', 'Tina');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (6, 6, 'pasillo', 'Melanie');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (7, 7, 'patio', 'Chantalle');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (8, 8, 'terraza', 'Ross');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (9, 9, 'patio', 'Florella');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (10, 10, 'habitación 2', 'Etta');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (11, 11, 'habitación 3', 'Merle');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (12, 12, 'pasillo', 'Gran');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (13, 13, 'terraza', 'Lishe');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (14, 14, 'pasillo', 'Steward');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (15, 15, 'terraza', 'Gennie');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (16, 16, 'pasillo', 'Benjie');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (17, 17, 'baño', 'Prudi');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (18, 18, 'baño', 'Valentijn');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (19, 19, 'patio', 'Maxie');
insert into huertos (IdHuerto, UsuarioPropietario, Localización, NombreHuerto) values (20, 20, 'pasillo', 'Virgie');
