INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (1,4,'terraza','Dallas');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (2,4,'patio','Millisent');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (3,4,'terraza','Artur');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (4,4,'baño','Ebba');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (5,5,'habitación 1','Tina');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (6,6,'pasillo','Melanie');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (7,7,'patio','Chantalle');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (21,21,'castillo1','charlie1');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (22,22,'castillo2','eden');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (23,23,'terraza','eden');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (24,24,'patio','merry');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (25,24,'atico','chopper');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (26,24,'pasillo','patitodegoma');
INSERT INTO `huertos` (`IdHuerto`,`UsuarioPropietario`,`Localización`,`NombreHuerto`) VALUES (27,24,'salon','relax');
