openapi: 3.0.3
info:
  title: Proyecto02-Grupo09
  description: Proyecto02-Grupo09
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /medidas/{id}:
    get:
      summary: Devuelve todas les medidas de un determinado usuario
      tags:
        - usuario
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Id numérico del usuario






      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/medidas"
        '401':
          description: No autorizado
        '404':
          description: Usuario no encontrado, Medidas no encontradas
        '5XX':
          description: Error del servidor


  
components:
  schemas:
      medidas:
        type: object
        properties:
          fecha:
            type: string
            description: fecha de la medida
          medida:
            type: number
            description: valor de la medida
          tipoMedida:
            type: string
            description: tipo de la medida (ph, sal, etc)
